# Generated by Django 5.2.3 on 2026-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_problem_genie_chat_problem_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemtestcase",
            name="drive_input_file_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="problemtestcase",
            name="drive_output_file_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
